### ISSUE TITLE
Description shouldn't reuse summary

### ISSUE THREAD

**Issue by razzeee** [flathub/com.pikatorrent.PikaTorrent#1]
There is a part in your description, thats already  used in the summary. Would be best to remove it.

**Comment by G-Ray** [comment]
Thank you @razzeee.
It seems the description can not start with a `<ul>` list, so I replaced the description paragraph with "Supercharge your torrents with PikaTorrent ⚡" upstream: https://github.com/G-Ray/pikatorrent/commit/25576ec88115a0604af8afcd9a329fb4706bf2fe
